"""002_task_lifecycle_recovery

Revision ID: 3acae1929949
Revises: 636b0ec3f801
Create Date: 2026-10-04 15:11:33.977160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3acae1929949'
down_revision = '636b0ec3f801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.String(length=35), nullable=False),
    sa.Column('used', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_reset_token_hash', ['token_hash'], unique=False)
        batch_op.create_index('idx_reset_token_user_pending', ['user_id', 'used'], unique=False)

    with op.batch_alter_table(
        'tasks',
        schema=None,
        table_args=(
            sa.CheckConstraint("status IN ('pendiente', 'en_progreso', 'completada')", name='chk_tasks_status'),
        )
    ) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.String(length=35), nullable=True))
        batch_op.create_index('idx_tasks_user_active', ['user_id', 'is_deleted', 'created_at'], unique=False)

    with op.batch_alter_table(
        'audit_logs',
        recreate='always',
        schema=None,
        table_args=(
            sa.CheckConstraint("action IN ('create', 'update', 'status_change', 'delete', 'reopen')", name='chk_audit_logs_action'),
        )
    ) as batch_op:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_user_active')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_reset_token_user_pending')
        batch_op.drop_index('idx_reset_token_hash')

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
