"""001_initial_schema

Revision ID: 636b0ec3f801
Revises: 
Create Date: 2026-10-04 15:08:59.684082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636b0ec3f801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('due_date', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.Column('updated_at', sa.String(length=35), nullable=False),
    sa.CheckConstraint("status IN ('pendiente', 'en_progreso', 'completada')", name='chk_tasks_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_tasks_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_tasks_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_tasks_user_status', ['user_id', 'status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=35), nullable=False),
    sa.CheckConstraint("action IN ('create', 'update', 'status_change')", name='chk_audit_logs_action'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_actor', ['actor_id'], unique=False)
        batch_op.create_index('idx_audit_logs_task', ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_logs_task')
        batch_op.drop_index('idx_audit_logs_actor')

    op.drop_table('audit_logs')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_tasks_user_status')
        batch_op.drop_index('idx_tasks_user_id')
        batch_op.drop_index('idx_tasks_user_created')

    op.drop_table('tasks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_email')

    op.drop_table('users')
    # ### end Alembic commands ###
